# Generated by Django 3.0.5 on 2020-06-03 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cart',
            field=models.CharField(max_length=15, null=True, verbose_name='카트아이디'),
        ),
    ]
