# Generated by Django 3.0.5 on 2020-06-03 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='cart',
            new_name='cart_id',
        ),
    ]
