# Generated by Django 3.0.5 on 2020-05-29 05:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chart_rank', models.CharField(blank=True, max_length=20, verbose_name='우선순위')),
                ('chart_title', models.CharField(max_length=128, verbose_name='차트 이름')),
                ('chart_url', models.TextField(verbose_name='차트 URL')),
                ('chart_register', models.DateTimeField(auto_now=True, verbose_name='등록 시간')),
                ('chart_writer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'verbose_name': '차트설정 메뉴',
                'verbose_name_plural': '차트설정 메뉴',
                'db_table': '차트설정 메뉴',
            },
        ),
    ]
