# Generated by Django 3.0.5 on 2020-06-01 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='menu_rank',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='우선순위'),
        ),
    ]
